
= Results overview

For each sample the pipeline creates a folder with sample ID name to write results, and produce a number of files. 

Result files for this workshop can be found in the folder with name `ENCSR000COQ/`. 

There you should see following files:


Variant calls::

* final.vcf
This file contains all somatic variants (SNVs) called from RNAseq data. You will see variants that pass all filters, with the 'PASS' keyword in the 7th field of the vcf file (filter status), and also those that has not passed one or few filters.


* diff.sites_in_files 	
Tabular separated file with comparison between variants obtained from RNAseq and DNA data, "known" variants

* known_snps.vcf 	
Variants that are common between RNAseq and DNA calls, "known" variants

Allele specific expression quantification::
* ASE.tsv 	
Tabular separated file with allele counts at a positions of SNVs (only for common SNVs,those from file known_snps.vcf)

Allele frequency histogram::

* AF.histogram.pdf 	
a histogram plot for allele frequency (only for common SNVs)

 
